version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "roots/wordpress"
        update-types: ["version-update:semver-major"]
    groups: # group together all roots related updates
      roots:
        patterns:
          - "roots/*"
  - package-ecosystem: "npm"
    directory: "/web/app/themes/wptesting/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
