version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "composer"
      - "wordpress"
      - "dependencies"
    groups: # group together all roots related updates
      roots:
        patterns:
          - "roots/*"
  - package-ecosystem: "npm"
    directory: "/web/app/themes/wptesting/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
